# -*- coding: utf-8 -*-
"""Audit Junk Keywords - Google Ads CSV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XXwCD3Y0q7beIulBs4GRn5N8_mihxfxT
"""

import csv

csv_file = "search_terms.csv"

MAX_SPEND_NO_CONV = 45.0
MIN_CLICKS_NO_CONV = 12

junk_words = ["free", "login", "portal", "careers", "reddit", "pdf", "tutorial", "template"]

print(">>> Scanning your search terms...")

wasted_queries = []
total_money_burnt = 0.0

with open(csv_file, mode="r", encoding="utf-8-sig") as f:
    reader = csv.DictReader(f)

    for row in reader:
        query = row.get("Search term", "").strip()
        cost_raw = row.get("Cost", "0").replace("$", "").replace(",", "")
        conv_raw = row.get("Conversions", "0").replace(",", "")
        clicks_raw = row.get("Clicks", "0").replace(",", "")

        try:
            cost = float(cost_raw)
            convs = float(conv_raw)
            clicks = int(clicks_raw)
        except ValueError:
            continue

        is_bleeding = (convs == 0) and (cost >= MAX_SPEND_NO_CONV or clicks >= MIN_CLICKS_NO_CONV)
        has_junk_token = any(word in query.lower().split() for word in junk_words)

        if is_bleeding or (has_junk_token and convs == 0):
            wasted_queries.append({
                "term": query,
                "cost": cost,
                "clicks": clicks
            })
            total_money_burnt += cost

wasted_queries.sort(key=lambda x: x["cost"], reverse=True)

print(f"\nFound {len(wasted_queries)} terms wasting cash.")
print(f"Total budget burned: ${total_money_burnt:,.2f}\n")

with open("add_to_negatives.txt", "w", encoding="utf-8") as out:
    for item in wasted_queries:
        out.write(f"[{item['term']}]\n")

print("Done! Open 'add_to_negatives.txt', copy all, and paste into your Negative Keyword List.")